### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by prismspecs** [andrewjeminchoi/simple-face-average#1]
Processing file: presidents\barak-obama.jpg
Number of faces detected: 1
Detection 0: Left: 354 Top: 354 Right: 1019 Bottom: 1020
Part 0: (352, 576), Part 1: (359, 664) ...
Traceback (most recent call last):
  File "F:\workbench\simple-face-average\face_landmark_detection.py", line 99, in <module>
    for i in xrange(0, 68):
NameError: name 'xrange' is not defined

**Comment by andrewjeminchoi** [comment]
Perhaps you are trying to run in Python3? `xrange` is only in Python 2.x
